# This is a basic workflow that is manually triggered

name: Build custom image

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      imageName:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Name of the final image'
        # Default value if no value is explicitly provided
        default: 'wirepas_raspberry_image'
        # Input has to be provided for the workflow to run
        required: true
      baseImage:
        description: 'Set to lite to use lite base image instead of Desktop'
        default: ''

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Call the script
        run: sudo ./create_image.sh ${{ github.event.inputs.imageName }} tmp ${{ github.event.inputs.baseImage }}
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: tmp/${{ github.event.inputs.imageName }}.zip
